// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rh01/gofiles/test/infra/db (interfaces: Repository)

// Package mock_db is a generated GoMock package.
package mock_db

import (
	"testing"
    . "github.com/golang/mock/gomock"
    "test/mock/db"
    ...
)


